### ISSUE TITLE
Configure `Metrics/BlockLength` with sensible Rails defaults

### ISSUE THREAD

**Issue by jgarber623-cargosense** [CargoSense/rubocop-cargosense#85]
I've found a handful of blocks that are necessarily long and not easily avoidable:

- `Rails.application.configure`
- `Rails.routes.draw` (and `namespace` within the routes file)
- `reversible` in database migrations
- `task` in a `*.rake` file

It's not terribly helpful to have RuboCop shout about those, so I'm proposing we add the following to our default metrics configuration here to avoid the noise:

```yaml
Metrics/BlockLength:
  AllowedMethods:
    - configure
    - draw
    - namespace
    - reversible
    - task
```
