### ISSUE TITLE
Configure `Metrics/MethodLength` with sensible Rails defaults

### ISSUE THREAD

**Issue by jgarber623-cargosense** [CargoSense/rubocop-cargosense#86]
Similar to #85, the change here quiets down RuboCop in database migrations (where `def change` is the default):

```yaml
Metrics/MethodLength:
  AllowedMethods:
    - change
```
